apiVersion: v1
kind: Service
metadata:
  name: aero
  namespace: aero
  labels:
    app: aero
spec:
  clusterIP: None
  selector:
    app: aero
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aero
  namespace: aero
  labels:
    app: aero
spec:
  replicas: 16
  selector:
    matchLabels:
      app: aero
  template:
    metadata:
      labels:
        app: aero
    spec:
      containers:
      - name: aero
        image: "registry.farfrom.earth:5555/aero/aero:latest"
        envFrom:
        - configMapRef:
            name: aero-config
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 15
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 15
          failureThreshold: 10
        lifecycle:
          preStop:
            httpGet:
              path: "/shutdown"
              port: 4000
              scheme: HTTP
        ports:
        - containerPort: 4000
  serviceName: "aero"
  podManagementPolicy: Parallel
