image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  TEST_IMAGE: registry.farfrom.earth:5555/aero/aero:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.farfrom.earth:5555

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
