image: docker:latest
services:
- docker:dind

stages:
- build
- deploy

variables:
  IMAGE: registry.farfrom.earth:5555/aero/aero:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.farfrom.earth:5555

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  script:
    - kubectl -n aero patch statefulset aero --type='json' -p='[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"$IMAGE"}]'
  only:
    - master
