stages:
- build
- deploy

variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  script:
    - kubectl -n aero patch statefulset aero --type='json' -p='[{"op":"replace", "path":"/spec/template/spec/containers/0/image", "value":"$IMAGE"}]'
  only:
    - master
