stages:
- build
- deploy

variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
  KUBECONFIG: /etc/deploy/config
  PATCH: \'{"spec":{"template":{"spec":{"containers":[{"name":"aero","image":"${IMAGE}"}]}}}}'

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  before_script:
    - mkdir -p /etc/deploy
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context default
  script:
    - echo $PATCH
    - kubectl -n aero patch statefulset aero --patch $PATCH
  only:
    - master
